language: objective-c
osx_image: xcode11.4
xcode_workspace: JSONValue.xcodeproj
xcode_scheme: JSONValue-Package
xcode_sdk: iphonesimulator11.4
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project JSONValue.xcodeproj -scheme JSONValue-Package -sdk iphonesimulator -destination "OS=10.2,name=iPhone 5S" ONLY_ACTIVE_ARCH=NO build test
