language: objective-c
osx_image: xcode10
xcode_workspace: JSONValue.xcodeproj
xcode_scheme: JSONValue-Package
xcode_sdk: iphonesimulator12.0
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -project JSONValue.xcodeproj -scheme JSONValue-Package -sdk iphonesimulator -destination "OS=12.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO build test
